import fs from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";
import { findRelease } from "../../../../lib/releases.js";
export const runtime="nodejs";export const dynamic="force-dynamic";
function releaseDirectories(){return[process.env.JARVIS_RELEASE_DIR,path.resolve(process.cwd(),"..","JarvisAssistant","dist"),path.resolve(process.cwd(),"public","downloads")].filter(Boolean)}
async function resolveRelease(filename){const release=findRelease(filename);if(!release)return null;for(const directory of releaseDirectories()){const candidate=path.join(directory,release.filename);try{const stat=await fs.promises.stat(candidate);if(stat.isFile())return{release,candidate,stat}}catch{}}return{release}}
function headersFor(release,size){return{"Content-Type":release.platform==="android"?"application/vnd.android.package-archive":"application/vnd.microsoft.portable-executable","Content-Disposition":`attachment; filename="${release.filename}"`,"Accept-Ranges":"bytes","Cache-Control":"public, max-age=3600, immutable","X-Content-Type-Options":"nosniff","X-Release-SHA256":release.sha256,"Content-Length":String(size)}}
export async function GET(request,{params}){const{filename}=await params;const resolved=await resolveRelease(filename);if(!resolved)return Response.json({error:"Unknown JARVIS release."},{status:404});if(!resolved.candidate){const base=(process.env.DOWNLOAD_BASE_URL||"https://github.com/isabekdanial33-gif/jarvis-download-center/releases/download/downloads").replace(/\/$/,"");return Response.redirect(`${base}/${encodeURIComponent(resolved.release.filename)}`,307)}const range=request.headers.get("range");if(range){const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)return new Response(null,{status:416,headers:{"Content-Range":`bytes */${resolved.stat.size}`}});const start=Number(match[1]);const end=match[2]?Math.min(Number(match[2]),resolved.stat.size-1):resolved.stat.size-1;if(start>end||start>=resolved.stat.size)return new Response(null,{status:416,headers:{"Content-Range":`bytes */${resolved.stat.size}`}});const stream=fs.createReadStream(/* turbopackIgnore: true */resolved.candidate,{start,end});return new Response(Readable.toWeb(stream),{status:206,headers:{...headersFor(resolved.release,end-start+1),"Content-Range":`bytes ${start}-${end}/${resolved.stat.size}`}})}return new Response(Readable.toWeb(fs.createReadStream(/* turbopackIgnore: true */resolved.candidate)),{headers:headersFor(resolved.release,resolved.stat.size)})}
export async function HEAD(_request,{params}){const{filename}=await params;const resolved=await resolveRelease(filename);if(!resolved?.candidate)return new Response(null,{status:resolved?503:404});return new Response(null,{headers:headersFor(resolved.release,resolved.stat.size)})}
